name: arteriaapp
description: Favorite Books
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependency_overrides:
  analyzer: 6.4.1
  meta: ^1.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  get: ^4.6.6
  flutter_bloc: ^8.1.4
  fluro: ^2.0.5
  flutter_keyboard_visibility: ^6.0.0
  overlay_support: ^2.1.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  http: ^1.2.0
  # utilities
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  freezed: ^2.4.6
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  build_resolvers: ^2.4.2

flutter:
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700

  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/
